title: "백엔드 개발자 hi4579675의 포트폴리오"
url: "https://hi4579675.github.io"
baseurl: ""

# Plugins
plugins:
  - jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging

# Bookshop configuration
# 로컬 경로 대신 현재 폴더 기준으로 수정 (에러 방지)
bookshop_locations:
  - component-library

exclude:
  - postcss.config.js
  - node_modules
  - .cloudcannon
  - Gemfile
  - Gemfile.lock

include:
  - _cloudcannon

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title
  projects:
    output: true
    permalink: /project/:slug
  testimonials:
    output: false
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title
