source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.9.0"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak", "~> 0.3"
end
