source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", "2.2.3"
  gem "cloudcannon-jekyll-bookshop", "2.2.3"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-sass-converter', :git => "https://github.com/CloudCannon/jekyll-sass-converter.git"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak", "~> 0.3"
end
