# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Posts List
  description: Lists all of the site's blog posts
  icon: wysiwyg
  tags:
    - Collections

# Defines the structure of this component, as well as the default values
blueprint:
  show_posts: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview: {}

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
